<?php

//DEFINE LOGO AND PROFILE IMAGE WIDTH 
DEFINE('IMG_WIDTH',500);
DEFINE('THUMB_WIDTH',140);
DEFINE('ICON_WIDTH',60);

//DEFINE SMTP DETAILS
DEFINE('SMTP_HOST','mailtrap.io');
DEFINE('SMTP_PORT',2525);
DEFINE('SMTP_USER','6306868d6d2ba2');
DEFINE('SMTP_PASS','0c3864a860861c');
DEFINE('SMTP_SECURE','tls');
DEFINE('SMTP_STATUS','1');

// DEFINE SITE DETAILS 
DEFINE('BLOG_NAME','Prospects Trails');
DEFINE('ADMIN_EMAIL','info@prospectstrails.com');
DEFINE('NO_REPLY','no-reply@prospectstrails.com');

?>